name: build

on: 
  push:
    paths: 
      - build/**
      - .github/workflows/build.yml

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install NDK
      run: |
        cd ~
        wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip
        sudo apt install unzip -y
        unzip -q NDK
        ANDROID_NDK_HOME=$(pwd)/android-ndk-r15c
    - name: Build
      run: |
        cd build
        chmod 777 make_android_lua54.sh
        ./make_android_lua54.sh
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        path: ./plugin_lua54/**/*
        name: plugin_lua54
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cd build
        chmod 777 make_linux_lua54.sh
        ./make_linux_lua54.sh
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        path: ./plugin_lua54/**/*
        name: plugin_lua54
  ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd build
          chmod 777 make_ios_lua54.sh
          ./make_ios_lua54.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./plugin_lua54/**/*
          name: plugin_lua54
  osx:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd build
          chmod 777 make_osx_lua54.sh
          ./make_osx_lua54.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./plugin_lua54/**/*
          name: plugin_lua54
  windows:
    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2

    - name: Insatll MSVC
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      run: |
        cd build
        .\make_win_lua54.bat
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        path: ./plugin_lua54/**/*
        name: plugin_lua54

   
